spring:
  application:
    name: company-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
